### PR TITLE
.PO and .MO files for French translation (translated at 100%)

### PR DESCRIPTION
**Pull request by JN-Squire**
French translation added (comics are very popular in French speaking Europe so and a lot of French artists don't speak or read English very well).

Translated at 100% with the Loco Translate plugin.

### CODE REVIEW

**Comment by JN-Squire** [comment]
Loco Translate mistakenly named the files comic-easel-fr_FR.mo and comic-easel-fr_FR.po instead of en_US.mo and en_US.po ... :(

**Comment by Frumph** [comment]
erm you mean fr_FR.mo and fr_FR.po right?

**Comment by Frumph** [comment]
As said, the comiceasel-en_US files were changed / updated and this needs to be updated with those;  can get a fresh copy by downloading it from here

**Comment by JN-Squire** [comment]
Is there still content for ComicPressin in the comiceasel-en_US.po/comiceasel-en_US.mo files. Since the code has been changed to address this issue, I'm not so sure anymore.

If it has been removed, then I'll wait for the regular plugin update for "my" comic translation (I don't have access to the server). Then I'll use Loca Translate again in order to get a full French translation of the plugin.

**Pull request closed without merging**
